/**
 * THE WORLD MAP'S GRAPH: which of Tenka's forty-two territories touch which.
 * Eighty-three pairs, the same graph as the classic world-conquest board
 * (John, 2026-10-02: "I only want equal to the original"). Only geography is
 * used: place names and who borders whom are facts, and no board, art or
 * wording of any published game is. Keys are `scripts/map-world.mjs`'s.
 *
 * Both `scripts/map.mjs` (which fails when the drawn map disagrees) and
 * `src/tenkaClassic.test.ts` read this one list.
 */
export const CLASSIC_EDGES = [
  // North America
  ["alaska", "northwestTerritory"],
  ["alaska", "alberta"],
  ["alaska", "kamchatka"],
  ["northwestTerritory", "alberta"],
  ["northwestTerritory", "ontario"],
  ["northwestTerritory", "greenland"],
  ["alberta", "ontario"],
  ["alberta", "westernUnitedStates"],
  ["ontario", "greenland"],
  ["ontario", "quebec"],
  ["ontario", "westernUnitedStates"],
  ["ontario", "easternUnitedStates"],
  ["quebec", "greenland"],
  ["quebec", "easternUnitedStates"],
  ["westernUnitedStates", "easternUnitedStates"],
  ["westernUnitedStates", "centralAmerica"],
  ["easternUnitedStates", "centralAmerica"],
  ["centralAmerica", "venezuela"],
  ["greenland", "iceland"],
  // South America
  ["venezuela", "peru"],
  ["venezuela", "brazil"],
  ["peru", "brazil"],
  ["peru", "argentina"],
  ["brazil", "argentina"],
  ["brazil", "northAfrica"],
  // Europe
  ["iceland", "greatBritain"],
  ["iceland", "scandinavia"],
  ["greatBritain", "scandinavia"],
  ["greatBritain", "northernEurope"],
  ["greatBritain", "westernEurope"],
  ["scandinavia", "northernEurope"],
  ["scandinavia", "ukraine"],
  ["northernEurope", "westernEurope"],
  ["northernEurope", "southernEurope"],
  ["northernEurope", "ukraine"],
  ["westernEurope", "southernEurope"],
  ["westernEurope", "northAfrica"],
  ["southernEurope", "ukraine"],
  ["southernEurope", "northAfrica"],
  ["southernEurope", "egypt"],
  ["southernEurope", "middleEast"],
  ["ukraine", "ural"],
  ["ukraine", "afghanistan"],
  ["ukraine", "middleEast"],
  // Africa
  ["northAfrica", "egypt"],
  ["northAfrica", "eastAfrica"],
  ["northAfrica", "congo"],
  ["egypt", "eastAfrica"],
  ["egypt", "middleEast"],
  ["eastAfrica", "congo"],
  ["eastAfrica", "southAfrica"],
  ["eastAfrica", "madagascar"],
  ["eastAfrica", "middleEast"],
  ["congo", "southAfrica"],
  ["southAfrica", "madagascar"],
  // Asia
  ["ural", "siberia"],
  ["ural", "china"],
  ["ural", "afghanistan"],
  ["siberia", "yakutsk"],
  ["siberia", "irkutsk"],
  ["siberia", "mongolia"],
  ["siberia", "china"],
  ["yakutsk", "irkutsk"],
  ["yakutsk", "kamchatka"],
  ["irkutsk", "kamchatka"],
  ["irkutsk", "mongolia"],
  ["kamchatka", "mongolia"],
  ["kamchatka", "japan"],
  ["mongolia", "japan"],
  ["mongolia", "china"],
  ["afghanistan", "china"],
  ["afghanistan", "india"],
  ["afghanistan", "middleEast"],
  ["china", "india"],
  ["china", "siam"],
  ["india", "middleEast"],
  ["india", "siam"],
  ["siam", "indonesia"],
  // Australia
  ["indonesia", "newGuinea"],
  ["indonesia", "westernAustralia"],
  ["newGuinea", "westernAustralia"],
  ["newGuinea", "easternAustralia"],
  ["westernAustralia", "easternAustralia"],
];
