/**
 * EVERY WORD TENKA SHOWS A PERSON, in English and Japanese: the table's
 * buttons and status lines, the names of the territories and continents, and
 * the lines of a game's written record (`tenkaToText`).
 *
 * A page in another language passes its own table, whole or in part:
 * `{ ...TENKA_STRINGS.en, endTurn: "Terminar turno" }`. `{n}`, `{name}` and
 * the other braces are filled in when a line is shown; a table must keep
 * them. `docs/strings-ja.md` lists the two languages side by side and is
 * made from this file.
 */

/** The languages the package speaks: English and Japanese. */
export type TenkaLocale = "en" | "ja";

const EN = {
  you: "You",
  player: "Player {n}",
  mapLabel: "Map of the world",
  lookAt: "Look at",
  world: "World",
  armiesLabel: "Armies",
  newGame: "New game",
  trade: "Trade cards",
  tradeMust: "Trade cards (you must)",
  allOn: "All {n} on {land}",
  attackWithOne: "Attack with 1 die",
  attackWith: "Attack with {n} dice",
  blitz: "Blitz",
  stopAttacking: "Stop attacking",
  moveIn: "Move {n} in",
  moveTo: "Move {n} to {land}",
  endTurn: "End turn",
  wins: "{name} takes the world.",
  tie: "A tie between {names}.",
  and: " and ",
  listComma: ", ",
  sentenceGap: " ",
  round: "Round {n} of {of}.",
  thinking: "{name} is playing…",
  setUpSay: "{name}: place an army on one of your territories ({n} left).",
  mustTradeSay: "{name}: five cards or more, so trade a set first.",
  placeOne: "{name}: place 1 army on your territories.",
  placeSay: "{name}: place {n} armies on your territories.",
  attackFrom: "{name}: tap a territory of yours with two armies or more to attack from, or stop attacking.",
  attackTo: "{name}: attacking from {land}. Tap a neighbour to attack.",
  attackReady: "{name}: {from} attacks {to}.",
  occupySay: "{name}: {land} is taken. How many move in?",
  fortifyFrom: "{name}: move armies once between two of your joined territories, or end your turn.",
  fortifyTo: "{name}: moving from {land}. Tap where to.",
  fortifyReady: "{name}: from {from} to {to}.",
  against: "against",
  rollThrows: ", {n} throws",
  rollLost: ": attacker lost {a}, defender lost {d}",
  rollTook: ", taken",
  counts: "{lands} lands, {armies} armies, {cards} cards",
  noCards: "No cards in hand ({name}).",
  cardsInHand: "Cards in hand ({name})",
  wild: "Wild",
  kindLand: "Land",
  kindSea: "Sea",
  kindAir: "Air",
  card: "{kind}: {land}",
  record: "Record of the game",
  recordEmpty: "No moves yet.",
  saveJson: "Save as JSON",
  saveText: "Save as text",
  saveCsv: "Save as CSV",
  load: "Load a game",
  loaded: "Game loaded: {n} moves.",
  loadBad: "That file is not a game of Tenka these rules can replay.",
  logTitle: "Tenka: {players}; {rounds} rounds; seed {seed}",
  logRound: "Round {n}",
  logPlace: "{name} places {n} on {land}.",
  logTrade: "{name} trades three cards for {n} armies.",
  logTradeBonus: "Two more on {land}.",
  logAttack: "{name}: {from} attacks {to}, [{a}] against [{d}]: attacker lost {al}, defender lost {dl}.",
  logBlitz: "{name}: {from} attacks {to} until it is decided, {n} throws: attacker lost {al}, defender lost {dl}.",
  logTook: "{land} is taken.",
  logOut: "{name} is out.",
  logOccupy: "{name} moves {n} in.",
  logEndAttack: "{name} stops attacking.",
  logFortify: "{name} moves {n} from {from} to {to}.",
  logEndTurn: "{name} ends the turn.",
  logCard: "{name} draws a card.",
  logCounted: "The game is counted after round {n}. Winner: {names}.",
  cNorthAmerica: "North America",
  cSouthAmerica: "South America",
  cEurope: "Europe",
  cAfrica: "Africa",
  cAsia: "Asia",
  cOceania: "Oceania",
  tAlaska: "Alaska",
  tWesternCanada: "Western Canada",
  tEasternCanada: "Eastern Canada",
  tArcticIslands: "Arctic Islands",
  tGreenland: "Greenland",
  tUsWest: "Western United States",
  tUsEast: "Eastern United States",
  tMexico: "Mexico and Central America",
  tColombia: "Colombia and Venezuela",
  tAndes: "The Andes",
  tBrazil: "Brazil",
  tSouthernCone: "Southern Cone",
  tBritain: "Britain and Ireland",
  tNordic: "The Nordic Countries",
  tWesternEurope: "Western Europe",
  tCentralEurope: "Central Europe",
  tSouthernEurope: "Southern Europe",
  tEasternEurope: "Eastern Europe",
  tWesternRussia: "Western Russia",
  tNorthAfrica: "North Africa",
  tEgypt: "Egypt and Sudan",
  tWestAfrica: "West Africa",
  tCentralAfrica: "Central Africa",
  tEastAfrica: "East Africa",
  tSouthernAfrica: "Southern Africa",
  tMadagascar: "Madagascar",
  tMiddleEast: "The Middle East",
  tArabia: "Arabia",
  tCentralAsia: "Central Asia",
  tSouthAsia: "South Asia",
  tSiberia: "Siberia",
  tFarEast: "The Russian Far East",
  tMongolia: "Mongolia",
  tChina: "China",
  tKorea: "Korea",
  tJapan: "Japan",
  tSoutheastAsia: "Southeast Asia",
  tIndonesia: "Indonesia",
  tMelanesia: "Melanesia",
  tWesternAustralia: "Western Australia",
  tEasternAustralia: "Eastern Australia",
  tNewZealand: "New Zealand",
};

/** Every word the package shows, by name: one table of these for each language. */
export type TenkaStrings = { [Name in keyof typeof EN]: string };

const JA: TenkaStrings = {
  you: "あなた",
  player: "プレイヤー{n}",
  mapLabel: "世界地図",
  lookAt: "表示する地域",
  world: "世界",
  armiesLabel: "部隊の数",
  newGame: "新しいゲーム",
  trade: "カードを交換",
  tradeMust: "カードを交換（必須）",
  allOn: "残りの{n}部隊をすべて{land}に置く",
  attackWithOne: "ダイス1個で攻撃",
  attackWith: "ダイス{n}個で攻撃",
  blitz: "決着がつくまで攻撃",
  stopAttacking: "攻撃を終える",
  moveIn: "{n}部隊を進める",
  moveTo: "{n}部隊を{land}へ移動",
  endTurn: "手番を終える",
  wins: "{name}が天下を取りました。",
  tie: "{names}の引き分けです。",
  and: "と",
  listComma: "、",
  sentenceGap: "",
  round: "第{n}ラウンド（全{of}ラウンド）。",
  thinking: "{name}の手番です…",
  setUpSay: "{name}: 自分の領土に部隊を1つ置いてください（残り{n}）。",
  mustTradeSay: "{name}: カードが5枚以上あります。先にセットを交換してください。",
  placeOne: "{name}: 自分の領土に1部隊を置いてください。",
  placeSay: "{name}: 自分の領土に{n}部隊を置いてください。",
  attackFrom: "{name}: 攻撃元にする自分の領土（2部隊以上）をタップするか、攻撃を終えてください。",
  attackTo: "{name}: {land}から攻撃します。攻撃する隣の領土をタップしてください。",
  attackReady: "{name}: {from}から{to}を攻撃します。",
  occupySay: "{name}: {land}を占領しました。何部隊進めますか。",
  fortifyFrom: "{name}: つながっている自分の領土の間で、部隊を一度だけ移動できます。移動しないときは手番を終えてください。",
  fortifyTo: "{name}: {land}から移動します。移動先をタップしてください。",
  fortifyReady: "{name}: {from}から{to}へ。",
  against: "対",
  rollThrows: "、{n}回",
  rollLost: "：攻撃側 −{a}、防御側 −{d}",
  rollTook: "、占領",
  counts: "領土{lands}・部隊{armies}・カード{cards}枚",
  noCards: "手札はありません（{name}）。",
  cardsInHand: "手札（{name}）",
  wild: "ワイルド",
  kindLand: "陸",
  kindSea: "海",
  kindAir: "空",
  card: "{kind}：{land}",
  record: "ゲームの記録",
  recordEmpty: "まだ手はありません。",
  saveJson: "JSONで保存",
  saveText: "テキストで保存",
  saveCsv: "CSVで保存",
  load: "ゲームを読み込む",
  loaded: "ゲームを読み込みました（{n}手）。",
  loadBad: "このファイルは、再現できる天下のゲームではありません。",
  logTitle: "天下: {players}、{rounds}ラウンド、シード {seed}",
  logRound: "第{n}ラウンド",
  logPlace: "{name}が{land}に{n}部隊を置く。",
  logTrade: "{name}がカード3枚を{n}部隊と交換。",
  logTradeBonus: "{land}にさらに2部隊。",
  logAttack: "{name}: {from}が{to}を攻撃、[{a}] 対 [{d}]：攻撃側 −{al}、防御側 −{dl}。",
  logBlitz: "{name}: {from}が{to}を決着がつくまで攻撃（{n}回）：攻撃側 −{al}、防御側 −{dl}。",
  logTook: "{land}を占領。",
  logOut: "{name}は敗退。",
  logOccupy: "{name}が{n}部隊を進める。",
  logEndAttack: "{name}が攻撃を終える。",
  logFortify: "{name}が{from}から{to}へ{n}部隊を移動。",
  logEndTurn: "{name}が手番を終える。",
  logCard: "{name}がカードを1枚引く。",
  logCounted: "第{n}ラウンド終了で集計。勝者: {names}。",
  cNorthAmerica: "北アメリカ",
  cSouthAmerica: "南アメリカ",
  cEurope: "ヨーロッパ",
  cAfrica: "アフリカ",
  cAsia: "アジア",
  cOceania: "オセアニア",
  tAlaska: "アラスカ",
  tWesternCanada: "カナダ西部",
  tEasternCanada: "カナダ東部",
  tArcticIslands: "北極諸島",
  tGreenland: "グリーンランド",
  tUsWest: "アメリカ西部",
  tUsEast: "アメリカ東部",
  tMexico: "メキシコ・中央アメリカ",
  tColombia: "コロンビア・ベネズエラ",
  tAndes: "アンデス",
  tBrazil: "ブラジル",
  tSouthernCone: "南アメリカ南部",
  tBritain: "イギリス・アイルランド",
  tNordic: "北欧",
  tWesternEurope: "西ヨーロッパ",
  tCentralEurope: "中央ヨーロッパ",
  tSouthernEurope: "南ヨーロッパ",
  tEasternEurope: "東ヨーロッパ",
  tWesternRussia: "ロシア西部",
  tNorthAfrica: "北アフリカ",
  tEgypt: "エジプト・スーダン",
  tWestAfrica: "西アフリカ",
  tCentralAfrica: "中央アフリカ",
  tEastAfrica: "東アフリカ",
  tSouthernAfrica: "南部アフリカ",
  tMadagascar: "マダガスカル",
  tMiddleEast: "中東",
  tArabia: "アラビア",
  tCentralAsia: "中央アジア",
  tSouthAsia: "南アジア",
  tSiberia: "シベリア",
  tFarEast: "ロシア極東",
  tMongolia: "モンゴル",
  tChina: "中国",
  tKorea: "朝鮮半島",
  tJapan: "日本",
  tSoutheastAsia: "東南アジア",
  tIndonesia: "インドネシア",
  tMelanesia: "メラネシア",
  tWesternAustralia: "オーストラリア西部",
  tEasternAustralia: "オーストラリア東部",
  tNewZealand: "ニュージーランド",
};

/** The package's words in each language it speaks: `TENKA_STRINGS.en`, `TENKA_STRINGS.ja`. */
export const TENKA_STRINGS: Readonly<Record<TenkaLocale, TenkaStrings>> = { en: EN, ja: JA };

/** A line from a table of strings with its braces filled in: `tenkaSay(strings.moveIn, { n: 3 })` is "Move 3 in". A brace with no value is left as it is. */
export function tenkaSay(line: string, values: Readonly<Record<string, string | number>> = {}): string {
  return line.replace(/\{(\w+)\}/g, (whole, name: string) => (name in values ? String(values[name]) : whole));
}

/** The table of strings for a locale with a page's own words laid over it. An unknown locale is English. */
export function tenkaStrings(locale: TenkaLocale | string | undefined, own: Partial<TenkaStrings> = {}): TenkaStrings {
  const base = typeof locale === "string" && locale.toLowerCase().startsWith("ja") ? JA : EN;
  return { ...base, ...own };
}

const upperFirst = (key: string): string => key.charAt(0).toUpperCase() + key.slice(1);

/** A territory's name in a table of strings, by its key (`TENKA_TERRITORIES[n].key`, such as `"alaska"`); "" for a key that is no territory's. */
export function territoryNameIn(strings: TenkaStrings, key: string): string {
  return (strings as Record<string, string>)[`t${upperFirst(key)}`] ?? "";
}

/** A continent's name in a table of strings, by its key (`"northAmerica"`, `"asia"`…). */
export function continentNameIn(strings: TenkaStrings, key: string): string {
  return (strings as Record<string, string>)[`c${upperFirst(key)}`] ?? "";
}
