/*
 * WRITTEN BY scripts/map-europe.mjs, NEVER BY HAND: run it again to change the map.
 * From Natural Earth's admin-1 states and provinces at 1:10m, which is in the public domain
 * (naturalearthdata.com; https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_1_states_provinces.geojson).
 */
import type { TenkaTerritoryData } from "./tenka.types.ts";

/** Tenka's Europe, forty-nine territories in region order: each one's key, name, region, and neighbours by land and by sea (indices into this list). */
export const TENKA_EUROPE_TERRITORY_DATA: readonly TenkaTerritoryData[] = [
  { key: "scotland", name: "Scotland", continent: "britishIsles", land: [1], sea: [3, 4] },
  { key: "england", name: "England", continent: "britishIsles", land: [0, 2], sea: [17, 23] },
  { key: "wales", name: "Wales", continent: "britishIsles", land: [1], sea: [3] },
  { key: "ireland", name: "Ireland", continent: "britishIsles", land: [], sea: [0, 2, 18] },
  { key: "norway", name: "Norway", continent: "scandinavia", land: [5], sea: [0, 7] },
  { key: "sweden", name: "Sweden", continent: "scandinavia", land: [4, 6], sea: [7] },
  { key: "finland", name: "Finland", continent: "scandinavia", land: [5], sea: [43, 44] },
  { key: "denmark", name: "Denmark", continent: "scandinavia", land: [21, 22, 27, 39, 41], sea: [4, 5] },
  { key: "portugal", name: "Portugal", continent: "iberia", land: [9], sea: [] },
  { key: "leonCastile", name: "León-Castile", continent: "iberia", land: [8, 10, 12, 13], sea: [14, 18] },
  { key: "navarre", name: "Navarre", continent: "iberia", land: [9, 11, 12, 19], sea: [] },
  { key: "barcelona", name: "Barcelona", continent: "iberia", land: [10, 12, 19], sea: [20] },
  { key: "valencia", name: "Valencia", continent: "iberia", land: [9, 10, 11, 13], sea: [15] },
  { key: "granada", name: "Granada", continent: "iberia", land: [9, 12], sea: [] },
  { key: "morocco", name: "Morocco", continent: "maghreb", land: [15], sea: [9] },
  { key: "algeria", name: "Algeria", continent: "maghreb", land: [14, 16], sea: [12] },
  { key: "tunisia", name: "Tunisia", continent: "maghreb", land: [15], sea: [33, 36] },
  { key: "normandy", name: "Normandy", continent: "france", land: [18, 19], sea: [1] },
  { key: "brittany", name: "Brittany", continent: "france", land: [17, 19], sea: [3, 9] },
  { key: "france", name: "France", continent: "france", land: [10, 11, 17, 18, 20, 23], sea: [] },
  { key: "burgundy", name: "Burgundy", continent: "france", land: [19, 23, 25, 30], sea: [11] },
  { key: "friesland", name: "Friesland", continent: "germany", land: [7, 22, 23], sea: [] },
  { key: "saxony", name: "Saxony", continent: "germany", land: [7, 21, 23, 24, 27], sea: [] },
  { key: "lorraine", name: "Lorraine", continent: "germany", land: [19, 20, 21, 22, 24, 25], sea: [1] },
  { key: "franconia", name: "Franconia", continent: "germany", land: [22, 23, 25, 26, 27], sea: [] },
  { key: "swabia", name: "Swabia", continent: "germany", land: [20, 23, 24, 26, 30], sea: [] },
  { key: "bavaria", name: "Bavaria", continent: "centralEurope", land: [24, 25, 27, 28, 29, 30, 34], sea: [] },
  { key: "bohemia", name: "Bohemia", continent: "centralEurope", land: [7, 22, 24, 26, 28, 41], sea: [] },
  { key: "highlands", name: "Highlands", continent: "centralEurope", land: [26, 27, 29, 41], sea: [] },
  { key: "hungary", name: "Hungary", continent: "centralEurope", land: [26, 28, 34, 35, 37, 41, 48], sea: [] },
  { key: "lombardy", name: "Lombardy", continent: "italy", land: [20, 25, 26, 31], sea: [] },
  { key: "rome", name: "Rome", continent: "italy", land: [30, 32], sea: [33] },
  { key: "kingdomOfSicily", name: "Kingdom of Sicily", continent: "italy", land: [31], sea: [34] },
  { key: "sardinia", name: "Sardinia", continent: "italy", land: [], sea: [16, 31] },
  { key: "venice", name: "Venice", continent: "balkans", land: [26, 29, 35], sea: [32] },
  { key: "serbia", name: "Serbia", continent: "balkans", land: [29, 34, 36, 37], sea: [] },
  { key: "greece", name: "Greece", continent: "balkans", land: [35, 37, 38], sea: [16] },
  { key: "bulgaria", name: "Bulgaria", continent: "balkans", land: [29, 35, 36, 38, 48], sea: [] },
  { key: "turkey", name: "Turkey", continent: "balkans", land: [36, 37], sea: [] },
  { key: "pomerania", name: "Pomerania", continent: "baltic", land: [7, 40, 41], sea: [42] },
  { key: "prussia", name: "Prussia", continent: "baltic", land: [39, 41, 42, 46], sea: [] },
  { key: "poland", name: "Poland", continent: "baltic", land: [7, 27, 28, 29, 39, 40, 46, 47, 48], sea: [] },
  { key: "lithuania", name: "Lithuania", continent: "baltic", land: [40, 43, 45, 46], sea: [39] },
  { key: "estonia", name: "Estonia", continent: "baltic", land: [42, 44, 45], sea: [6] },
  { key: "novgorod", name: "Republic of Novgorod", continent: "easternEurope", land: [43, 45], sea: [6] },
  { key: "smolensk", name: "Smolensk", continent: "easternEurope", land: [42, 43, 44, 46, 47], sea: [] },
  { key: "polotsk", name: "Polotsk", continent: "easternEurope", land: [40, 41, 42, 45, 47], sea: [] },
  { key: "rusland", name: "Rusland", continent: "easternEurope", land: [41, 45, 46, 48], sea: [] },
  { key: "galicia", name: "Galicia", continent: "easternEurope", land: [29, 37, 41, 47], sea: [] },
];
